baseURL = "/"
languageCode = "en-us"
title = "Bengt's Blog"
theme = "hugo-clarity"

[params]
author = "bgronas"
twitter  = "bgronas"
largeTwitterCard = true
description = "Virtual Stuff for Virtual people"
introDescription = "Virtual Stuff for Virtual people"
introURL = true
numberOfTagsShown = 10
usePageBundles = false
fallBackOgImage  = ""
codeMaxLines = 12
codeLineNumbers = false
mainSections = ["post", "blog"]
# centerLogo = false
logo = "icons/apple-touch-icon.png"
iconsDir = "icons/logo.png"
mobileNavigation = "left"
figurePositionShow = true
# figurePositionLabel = 
# customCSS
# customJS
enforceLightMode = true
# enforceDarkMode
titleSeparator = "|"
showShare = true
comments = false
numberOfRecentPosts = 10
numberOfFeaturedPosts = 2
dateFormat = "Mon. 23-12-2020"
enableMathNotation = true
# customFonts
since = 2021
# rss_summary
# rss_summary_read_more_link
showRelatedInArticle = true
showRelatedInSidebar = true 
footerLogo = "icons/apple-touch-icon.png"

